export enum ErrorCodes {
  REQUIRED_FIELD = "REQUIRED_FIELD",
  INVALID_EMAIL = "INVALID_EMAIL",
  BAD_RESPONSE_BODY = "BAD_RESPONSE_BODY",
  HANDLING_RESPONSE_ERROR = "HANDLING_RESPONSE_ERROR",
  RESPONSE_VALIDATION_ERROR = "RESPONSE_VALIDATION_ERROR",
  FORM_VALIDATION_ERROR = "FORM_VALIDATION_ERROR",
  UKNOWN_ERROR = "UKNOWN_ERROR",
  TOO_SHORT = "TOO_SHORT",
  BAD_REQUEST = "BAD_REQUEST",
  FORBIDDEN = "FORBIDDEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  SERVER_ERROR = "SERVER_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  CONNECTION_ERROR = "CONNECTION_ERROR",
}

export const COOKIES_KEYS = {
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  USER_INFORMATION: "eo_rmnsutoifirna",
};
