export enum ErrorCodes {
  REQUIRED_FIELD = "REQUIRED_FIELD",
  INVALID_EMAIL = "INVALID_EMAIL",
  BAD_RESPONSE_BODY = "BAD_RESPONSE_BODY",
  HANDLING_RESPONSE_ERROR = "HANDLING_RESPONSE_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UKNOWN_ERROR = "UKNOWN_ERROR",
  TOO_SHORT = "TOO_SHORT",
  BAD_REQUEST = "BAD_REQUEST",
  FORBIDDEN = "FORBIDDEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  SERVER_ERROR = "SERVER_ERROR",
}
