import fs from "fs";
import path from "path";

/**
 * Generates TypeScript constant keys from translation JSON structure
 */
function generateKeysFromObject(obj: Record<string, any>, prefix: string = ""): string {
  let result = "";

  for (const [key, value] of Object.entries(obj)) {
    const constantKey = key.toUpperCase().replace(/-/g, "_");
    const fullPath = prefix ? `${prefix}.${key}` : key;

    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      // It's a nested object
      result += `    ${constantKey}: {\n`;
      result += generateKeysFromObject(value, fullPath)
        .split("\n")
        .map((line) => (line ? `  ${line}` : line))
        .join("\n");
      result += `    },\n`;
    } else {
      // It's a leaf node (actual translation key)
      result += `      ${constantKey}: "${fullPath}",\n`;
    }
  }

  return result;
}

/**
 * Loads all translation files recursively and merges them
 */
function loadTranslationsRecursively(dir: string, locale: string = "en"): Record<string, any> {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const translations: Record<string, any> = {};

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      // Recursively load from subdirectory
      translations[entry.name] = loadTranslationsRecursively(fullPath, locale);
    } else if (entry.isFile() && entry.name === `${locale}.json`) {
      // Load the locale file
      const fileContent = JSON.parse(fs.readFileSync(fullPath, "utf-8"));
      Object.assign(translations, fileContent);
    }
  }

  return translations;
}

/**
 * Main function to generate the translation keys file
 */
function generateTranslationKeys(messagesDir: string, outputPath: string, locale: string = "en"): void {
  console.log(`Loading translations from: ${messagesDir}`);

  const translations = loadTranslationsRecursively(messagesDir, locale);

  const fileContent = `/**
 * Auto-generated translation keys
 * Do not edit this file manually - it will be overwritten
 * Generated on: ${new Date().toISOString()}
 */

export const TRANSLATIONS_KEYS = {
${generateKeysFromObject(translations).trimEnd()}
};
`;

  fs.writeFileSync(outputPath, fileContent, "utf-8");
  console.log(`✅ Translation keys generated successfully at: ${outputPath}`);
}

// CLI Usage
if (require.main === module) {
  const messagesDir = path.join(process.cwd(), "src/i18n/messages");
  const outputPath = path.join(process.cwd(), "src/i18n/translation-keys.ts");
  const locale = process.argv[2] || "en"; // Allow specifying locale via CLI

  try {
    generateTranslationKeys(messagesDir, outputPath, locale);
  } catch (error) {
    console.error("❌ Error generating translation keys:", error);
    process.exit(1);
  }
}

export { generateTranslationKeys };
