export const PERMISSIONS = {
  // Users
  VIEW_USERS: "VU",
  MANAGE_USERS: "MU",

  // Roles
  VIEW_ROLES: "VR",
  MANAGE_ROLES: "MR",

  // Biens
  VIEW_BIENS: "VB",
  MANAGE_BIENS: "MB",

  // Clients
  VIEW_CLIENTS: "VCL",
  MANAGE_CLIENTS: "MCL",

  // Offers
  VIEW_OFFERS: "VOF",
  MANAGE_OFFERS: "MOF",

  // Demands
  VIEW_DEMANDS: "VD",
  MANAGE_DEMANDS: "MD",

  // Events
  VIEW_EVENTS: "VE",
  MANAGE_EVENTS: "ME",

  // Wilayas
  VIEW_WILAYAS: "VW",
  MANAGE_WILAYAS: "MW",

  // Communes
  VIEW_COMMUNES: "VCM",
  MANAGE_COMMUNES: "MCM",

  // Bien Types
  VIEW_BIEN_TYPES: "VBT",
  MANAGE_BIEN_TYPES: "MBT",

  // Bien Status
  VIEW_BIEN_STATUSES: "VBS",
  MANAGE_BIEN_STATUSES: "MBS",

  // Bien Priorities
  VIEW_BIEN_PRIORITIES: "VBP",
  MANAGE_BIEN_PRIORITIES: "MBP",

  // Bien Characteristics
  VIEW_BIEN_CHARACTERISTICS: "VBC",
  MANAGE_BIEN_CHARACTERISTICS: "MBC",

  // Client Types
  VIEW_CLIENT_TYPES: "VCT",
  MANAGE_CLIENT_TYPES: "MCT",

  // Client Status
  VIEW_CLIENT_STATUSES: "VCS",
  MANAGE_CLIENT_STATUSES: "MCS",

  // Client Sources
  VIEW_CLIENT_SOURCES: "VCSR",
  MANAGE_CLIENT_SOURCES: "MCSR",

  // Offer Types
  VIEW_OFFER_TYPES: "VOT",
  MANAGE_OFFER_TYPES: "MOT",

  // Offer Status
  VIEW_OFFER_STATUSES: "VOS",
  MANAGE_OFFER_STATUSES: "MOS",

  // Demand Sources
  VIEW_DEMAND_SOURCES: "VDSR",
  MANAGE_DEMAND_SOURCES: "MDSR",

  // Demand Types
  VIEW_DEMAND_TYPES: "VDT",
  MANAGE_DEMAND_TYPES: "MDT",

  // Demand Types
  VIEW_DEMAND_STATUES: "VDS",
  MANAGE_DEMAND_STATUES: "MDS",

  // Demand Status priorities
  VIEW_DEMAND_PRIORITY: "VDP",
  MANAGE_DEMAND_PRIORITY: "MDP",

  // Transaction types
  VIEW_TRANSACTION_TYPES: "VTT",
  MANAGE_TRANSACTION_TYPES: "MTT",

  // Events types
  VIEW_EVENTS_TYPES: "VET",
  MANAGE_EVENTS_TYPES: "MET",

  // Colors
  VIEW_COLORS: "VC",
  MANAGE_COLORS: "MC",

  // Documents (library)
  VIEW_DOCUMENTS: "VDOC",
  MANAGE_DOCUMENTS: "MDOC",
  VIEW_CONFIDENTIAL_DOCUMENTS: "VDOCC",

  // Notifications (centre + moteur)
  VIEW_NOTIFICATIONS: "VN",
  MANAGE_NOTIFICATIONS: "MN",

  // Statistics & reports
  VIEW_STATISTICS: "VSTAT",
  EXPORT_STATISTICS: "MSTAT",
};