export const PERMISSIONS = {
  // Users
  CREATE_USER: "CU",
  UPDATE_USER: "UU",
  DELETE_USER: "DU",
  VIEW_USER: "VU",
  VIEW_USERS: "VUS",

  // Roles
  CREATE_ROLE: "CR",
  UPDATE_ROLE: "UR",
  DELETE_ROLE: "DR",
  VIEW_ROLE: "VR",
  VIEW_ROLES: "VRS",

  // Biens
  CREATE_BIEN: "CB",
  UPDATE_BIEN: "UB",
  DELETE_BIEN: "DB",
  VIEW_BIEN: "VB",
  VIEW_BIENS: "VBS",

  // Clients
  CREATE_CLIENT: "CCL",
  UPDATE_CLIENT: "UCL",
  DELETE_CLIENT: "DCL",
  VIEW_CLIENT: "VCL",
  VIEW_CLIENTS: "VCLS",

  // Offers
  CREATE_OFFER: "COF",
  UPDATE_OFFER: "UOF",
  DELETE_OFFER: "DOF",
  VIEW_OFFER: "VOF",
  VIEW_OFFERS: "VOFS",

  // Demands
  CREATE_DEMAND: "CD",
  UPDATE_DEMAND: "UD",
  DELETE_DEMAND: "DD",
  VIEW_DEMAND: "VD",
  VIEW_DEMANDS: "VDS",

  // Events
  CREATE_EVENT: "CE",
  UPDATE_EVENT: "UE",
  DELETE_EVENT: "DE",
  VIEW_EVENT: "VE",
  VIEW_EVENTS: "VES",

  // Wilayas
  CREATE_WILAYA: "CW",
  UPDATE_WILAYA: "UW",
  DELETE_WILAYA: "DW",
  VIEW_WILAYA: "VW",
  VIEW_WILAYAS: "VWS",

  // Communes
  CREATE_COMMUNE: "CCM",
  UPDATE_COMMUNE: "UCM",
  DELETE_COMMUNE: "DCM",
  VIEW_COMMUNE: "VCM",
  VIEW_COMMUNES: "VCMS",

  // Bien Types
  CREATE_BIEN_TYPE: "CBT",
  UPDATE_BIEN_TYPE: "UBT",
  DELETE_BIEN_TYPE: "DBT",
  VIEW_BIEN_TYPE: "VBT",
  VIEW_BIEN_TYPES: "VBTS",

  // Bien Status
  CREATE_BIEN_STATUS: "CBS",
  UPDATE_BIEN_STATUS: "UBS",
  DELETE_BIEN_STATUS: "DBS",
  VIEW_BIEN_STATUS: "VBST",
  VIEW_BIEN_STATUSES: "VBSTS",

  // Bien Priorities
  CREATE_BIEN_PRIORITY: "CBP",
  UPDATE_BIEN_PRIORITY: "UBP",
  DELETE_BIEN_PRIORITY: "DBP",
  VIEW_BIEN_PRIORITY: "VBP",
  VIEW_BIEN_PRIORITIES: "VBPS",

  // Bien Characteristics
  CREATE_BIEN_CHARACTERISTIC: "CBC",
  UPDATE_BIEN_CHARACTERISTIC: "UBC",
  DELETE_BIEN_CHARACTERISTIC: "DBC",
  VIEW_BIEN_CHARACTERISTIC: "VBC",
  VIEW_BIEN_CHARACTERISTICS: "VBCS",

  // Client Types
  CREATE_CLIENT_TYPE: "CCT",
  UPDATE_CLIENT_TYPE: "UCT",
  DELETE_CLIENT_TYPE: "DCT",
  VIEW_CLIENT_TYPE: "VCT",
  VIEW_CLIENT_TYPES: "VCTS",

  // Client Status
  CREATE_CLIENT_STATUS: "CCS",
  UPDATE_CLIENT_STATUS: "UCS",
  DELETE_CLIENT_STATUS: "DCS",
  VIEW_CLIENT_STATUS: "VCST",
  VIEW_CLIENT_STATUSES: "VCSTS",

  // Client Sources
  CREATE_CLIENT_SOURCE: "CCSR",
  UPDATE_CLIENT_SOURCE: "UCSR",
  DELETE_CLIENT_SOURCE: "DCSR",
  VIEW_CLIENT_SOURCE: "VCSR",
  VIEW_CLIENT_SOURCES: "VCSRS",

  // Offer Types
  CREATE_OFFER_TYPE: "COT",
  UPDATE_OFFER_TYPE: "UOT",
  DELETE_OFFER_TYPE: "DOT",
  VIEW_OFFER_TYPE: "VOT",
  VIEW_OFFER_TYPES: "VOTS",

  // Offer Status
  CREATE_OFFER_STATUS: "COS",
  UPDATE_OFFER_STATUS: "UOS",
  DELETE_OFFER_STATUS: "DOS",
  VIEW_OFFER_STATUS: "VOST",
  VIEW_OFFER_STATUSES: "VOSTS",

  // Transaction Types
  CREATE_TRANSACTION_TYPE: "CTT",
  UPDATE_TRANSACTION_TYPE: "UTT",
  DELETE_TRANSACTION_TYPE: "DTT",
  VIEW_TRANSACTION_TYPE: "VTT",
  VIEW_TRANSACTION_TYPES: "VTTS",

  // Colors
  CREATE_COLOR: "CC",
  UPDATE_COLOR: "UC",
  DELETE_COLOR: "DC",
  VIEW_COLOR: "VC",
  VIEW_COLORS: "VCS",
};
